### ISSUE TITLE
Is there a way to use this on Synology NAS without use of Docker?

### ISSUE THREAD

**Issue by squatz1** [haijeploeg/excludarr#14]
Bought one of the low end Synology NAS's so it can't support Docker, just curious if that's possible.

If not, totally fine just wanted to ask the community before jumping in. I appreciate the help folks!

**Comment by haijeploeg** [comment]
Hi squatz,

Thank you for reaching out! Unfortunately I don't own a Synology NAS. But I know a few things about them. You should be able to install python3. If you enable SSH, you should be able to [install pip](https://techjogging.com/installing-and-using-pip-on-synology-dsm.html) and then install excludarr (`pip install excludarr`). If you have successfully installed that, you should be able to [setup a cronjob](https://knasmueller.net/configuring-cron-jobs-on-a-synology-nas).

Hope this helps, please let me know whenever you are stuck. I'm happy to help :)
