### ISSUE TITLE
Change Excluded to Monitored if not on streaming services

### ISSUE THREAD

**Issue by KaHooli** [haijeploeg/excludarr#15]
I'd like to see an option that would make movies/shows that are Excluded back to Monitored if they are no longer found on a streaming service.

I can imagine not everyone will want this option, hence it being optional. 😁

**Comment by haijeploeg** [comment]
Hi Kahooli,

I investigated this and this should be possible. I could check if the movie is blacklisted in radarr and retrieve all not monitored movies and set them to monitored.

I will try to develop another subcommand for this in the upcoming days.

**Comment by KaHooli** [comment]
> I can however read all not-monitored movies and set them back to monitored if they are not on a streaming provider anymore. Is that something you would like to see?

That sounds good 👍

**Comment by haijeploeg** [comment]
This has been added in version v0.1.5. You can upgrade using pip or docker :)
