### ISSUE TITLE
Dry run mode?

### ISSUE THREAD

**Issue by pven** [haijeploeg/excludarr#2]
Hi,

When I am right, there is no dry run mode in exclude_streaming_radarr. Is it possible to add this? I want to see which movies will be deleted, before they are really deleted in Radarr.

**Comment by haijeploeg** [comment]
Hi Pven,

That is correct, it is on my to do list. I will try to add this feature this week.

**Comment by haijeploeg** [comment]
Hi Pven,

I have just added a CLI tool. It took a little bit longer than I expected, but I decided to rewrite the tool to a more user friendly approach. You can now install the tool via: `pip install excludarr`. Please let me know if you encounter any other problems!
