### ISSUE TITLE
Sonarr episode search

### ISSUE THREAD

**Issue by KaHooli** [haijeploeg/excludarr#21]
It is possible to only remove episodes that are on the specified providers and mark that episode as excluded, rather than remove the whole show?

Reason I ask, is there are shows that in Australia takes weeks (or we are even a whole season behind sometimes), and so I'd like Sonarr to monitor and download episodes we can't get on our specified providers, but once we can have Excludarr remove them and mark them as excluded to save on drive space.

Thanks for the great work you've done so far, I'm using this for Radarr and it has saved me a lot of drive space!  If you can do episodes rather than whole shows, I look forward to using it with Sonarr as well.

**Comment by jokerigno** [comment]
Totally agree with this!

**Comment by haijeploeg** [comment]
I figured already that people would want that functionalitity :). However, the down side is that the TMDB api does not provide this information unfortunately. I am looking to Justwatch API. But that one is not documented, so I will need to debug a lot. I took already a quick look and it seems that they are providing the information.

I am putting this one for the release of version 1.0.0. In that version I want to completely rewrite the code and also make it possible to debug easier, for future bugs etc. Right now the codebase is a bit of a mess :). This can take a while to intergrate, so please be patient. I will try to release this version around christmas if I have enough time.

**Comment by haijeploeg** [comment]
A little status update. Currently I am busy rewriting the tool to make it more robust, stable and easier to manage. I am about 70% done right now, I only need to add a re add function for re monitoring series in Sonarr. 

The feature you are describing here has just been pushed to branch [feature/rewrite_typer](https://github.com/haijeploeg/excludarr/tree/feature/rewrite_typer). It is not installable yet, but I am planning to release this around christmas, so stay tuned! It is a big release with tons of adjustments, changes and features. Also a TMDB API is not mandatory needed anymore :)

**Comment by haijeploeg** [comment]
This has been added to Excludarr version 1.0.1. This version is just released, so you can upgrade now! It has tons of changes, so please read the CHANGELOG, README, FAQ en the example configuration files for changes. If you have questions or stumble upon bugs, feel free to create a new issue ticket.
