### ISSUE TITLE
Please add all cli options to the README

### ISSUE THREAD

**Issue by mduijm** [haijeploeg/excludarr#38]
Hi,

as I am using the docker file, it is not easy to see all cli commands. Perhaps you can document them online?

thanks for the tool! Going to have a test run now ;)

**Comment by haijeploeg** [comment]
Hi,

Thanks for testing it out! 

I'm not really sure what you mean, the commands are in the README.md file though. Is it unclear how to use the docker container? To see all the commands you can just run the docker container with the `--help` flag to get the help information of the command.

**Comment by haijeploeg** [comment]
Closed due inactivity.
