### ISSUE TITLE
Add Sonarr?

### ISSUE THREAD

**Issue by jokerigno** [haijeploeg/excludarr#4]
Hi,

do you think it would be possible to add same method also for Sonarr?

**Comment by haijeploeg** [comment]
Hi jokerigno,

I have thought about it. I am currently rewriting the whole script to a command line tool, so it will become easier to list, delete and configure :). Unfortunately lately I have a lot of other work to do, but I expect to pick up development of the script this week. When the basic functionalitity of Radarr is integrated in the tool, I will try to add Sonarr as well. 

I have to figure out if there is some API available that lists also series. Via the API of TMDB I cannot do that. I will come back to you as soon as I have a solution for this!

**Comment by jokerigno** [comment]
Great! For sonarr I think you can use TMDB as well: 

https://www.themoviedb.org/documentation/api

Or JustWatch for example.

**Comment by haijeploeg** [comment]
Hi Jokerigno,

You are right! I thought it was not available for the TV endpoint. https://developers.themoviedb.org/3/tv/get-tv-watch-providers. I will definitely integrate this :).

**Comment by jokerigno** [comment]
Hi, any update on using also sonarr?

Moreover are you thinking on a docker container to run it? Or how is the best way to run it?

**Comment by haijeploeg** [comment]
Hi Jokerigno,

No there is not an update for Sonarr yet. Lately I did not have a lot of spare time. In the beginning of May I have some free time again, I'm planning to intergrate this during those days.

I prefer to run this as a cronjob just on the system. I am planning to release a docker container as well that you can use.

**Comment by jokerigno** [comment]
Great news. I hope to have this and not_monitored (highlighted in another issue)to final have a lot of free space again!

**Comment by foXaCe** [comment]
hello, do you still have plans to adapt it to sonarr?

**Comment by haijeploeg** [comment]
I finally found the time to integrate this. You can check the progress in the linked PR.

**Comment by foXaCe** [comment]
hello
very good I'm waiting the merge

**Comment by haijeploeg** [comment]
This has been added in version 0.2.0. Sonarr is only supported on the exclude command yet. The check command will be later added. Let me know what you think of it!

**Comment by KaHooli** [comment]
It is possible to only remove episodes that are on the specified providers and mark that episode as excluded, rather than remove the whole show?

Reason I ask, is there are shows that in Australia takes weeks (or we are even a whole season behind sometimes), and so I'd like Sonarr to monitor and download episodes we can't get on our specified providers, but once we can have Excludarr remove them and mark them as excluded to save on drive space.
