### ISSUE TITLE
Exclude Amazon Prime Video That Is Not Free

### ISSUE THREAD

**Issue by gist901** [haijeploeg/excludarr#42]
Hi there,

Really love this feature, think this is something that is missing from Sonarr and Radarr. I have run this currently to test it and noticed I have alot of movies that show up as being available in Amazon Prime. However, many of the videos are only accessible via paying for the movie, not being free to access through Amazon Prime. I also noticed this on several movies that are available on Disney Plus, but are only accessible through Disney's additional pay wall for select / new theatrical releases.

I would love this feature to have the ability to check if there is an additional cost to the movie via certain providers and if there is a way to omit the removal of the movie / tv show.

**Comment by haijeploeg** [comment]
It seems that this is the same question as #33 . I checked it with his examples, but it seemed to work just fine at that moment. Maybe I've missed something. Could you provide your configuration file and provide examples of movies and series you have noticed?

Using that I can debug it and try if there is a solution for it. In the mean time you can exclude those movies and shows manually from being processed by Excludarr under the `exclude` setting in the `radarr` and `sonarr` config settings.

**Comment by gist901** [comment]
My apologies, once I changed my region from en_NL to en_US, it appears to be working as intended. I also now get a list of many more providers, which now makes sense. Thanks for all the hard work on this great feature. 

2 additional features that would be nice to see
 1. Just add a tag to movies
 2. Be able to export the list to a CSV

**Comment by haijeploeg** [comment]
No worries! The tag part is already a feature request #34 . Could you describe the other features more detailed using the Feature Request template?
