### ISSUE TITLE
Provide a docker image that works on arm64

### ISSUE THREAD

**Issue by alejakun** [haijeploeg/excludarr#45]
I'm trying to use excludarr, however my setup is all running in a raspberry pi 4 (arm64 processor). I'd really love to include this application in my setup since space is an issue and being a Python script I think it could be done relatively easy.

**Comment by haijeploeg** [comment]
Hi! Thanks for your request. Sounds like a plan! Never thought about it that the current one is not working on arm :). I will run some tests the upcoming days and try to add a dockerfile as soon as possible.

**Comment by alejakun** [comment]
Thanks for the promp request, I think it would be a valuable addition to the image (it would definitely be valuable for me). Best regards!

**Comment by haijeploeg** [comment]
Hi, I have changed the build workflow so that it now also creates a arm64 container. However I am not able to test this. Could you maybe test this for me? Version `v1.0.6` (or just `latest`) is build for arm64.

Looking forward to hear from you!

**Comment by alejakun** [comment]
I’ll test this today and report back to you as soon as I can 😉

**Comment by alejakun** [comment]
It seems to be working alright so far, I think it's safe to close the issue.

**Comment by haijeploeg** [comment]
Thanks for testing it out and glad that it works! So you are saying that the `SONARR_EXCLUDE="Queen of the South, Breaking Bad"` should be `SONARR_EXCLUDE=Queen of the South, Breaking Bad` in order to get it working?

**Comment by alejakun** [comment]
At least in my setup, yes

**Comment by haijeploeg** [comment]
Thanks! Will update it :)
