### ISSUE TITLE
Unmonitor the series and delete the files

### ISSUE THREAD

**Issue by alejakun** [haijeploeg/excludarr#48]
I'm not sure if I'm correct in this but for what I could get from the documentation the command can either delete the show (and optionally it's files), or unmonitor the show (always leaving the files), what I would like is an option to unmonitor the show AND delete the files. Maybe is just a misunderstanding of the documentation from my part and it is already possible.

**Comment by haijeploeg** [comment]
Hi! Thanks for your question! You can unmonitor and delete the files attached to the show or movie using:

```bash
excludarr radarr exclude -a not-monitored -d
excludarr sonarr exclude -a not-monitored -d
```

**Comment by alejakun** [comment]
Hi,

Thanks for the response, I laso noticed you use in the documentation examples a -e flag, what is this fore?

**Comment by haijeploeg** [comment]
The `-e` flag is only working with the `-a delete` action. Once it deletes a movie or TV show, it will also add an import exclusion to prevent automatically importing the movie or TV show again using a list.

**Comment by Vansmak** [comment]
If I may piggyback on this.  I am just starting out with this and ty for it.  I want shows that are on amazon prime to be unmonitored and delete files but when the show has ended only keep it in sonarr as unmonitored. 

i was using docker run -it --rm --env-file excludarr.env haijeploeg/excludarr:latest sonarr exclude -a delete -d -e

**Comment by foXaCe** [comment]
hello, everything works for me except the exclusion. the series comes back after loading my list.

i use sonarr .3.0.8.1540
