### ISSUE TITLE
Netflix streaming provider option not working in AU

### ISSUE THREAD

**Issue by KaHooli** [haijeploeg/excludarr#7]
As noted in my comment at https://github.com/haijeploeg/excludarr/issues/5#issuecomment-798721591 , the Netflix streaming provider option isn't working in AU.

See my linked post for more details, debug & log outputs.

**Comment by haijeploeg** [comment]
I will try to debug this, can you provide some movies that are available on Netflix in AU and not being deleted from Radarr?

**Comment by haijeploeg** [comment]
Hi, I have investigated this, but I can't seem to reproduce this. I have tried it with **Spider man 3** and **Outside the wire** And I adjusted my country to `AU`. But it seems that something else is wrong. Can you give me a few examples from your Radarr movie list that should be on Netflix but are not being deleted by this tool?

**Comment by KaHooli** [comment]
I've been looking into this for about a week now with the limited free time I have.  It appears all movies from Netflix have been removed, but were never reported in the output of the script.

Strange, and I'm still looking into it.

**Comment by haijeploeg** [comment]
Hi, I have looked into this issue as well, but I can't seem to find a bug here. If you cannot find any issue as well, please feel free to close this issue. Otherwise I'd like to hear which movies are not being deleted, so I can test this :)
