### ISSUE TITLE
Different country for different tags?

### ISSUE THREAD

**Issue by jcandresen** [haijeploeg/excludarr#70]
I'm sure this is such a niche use case and I was debating setting up two different sets of radarr/sonarr but is it possible to have excludarr to use language en_CA when NameA/NameB are tagged on a movies/series and use language da_DK if the tags NameC/NameD are on a movie? 

My brothers overseas are using it and they have different streaming options over there than we do in Canada.

**Comment by haijeploeg** [comment]
Hi, sorry for the late reply. The best thing to do is add another instance within an virtualenv or docker with the other settings. I think that is the cleanest solution here. I will not add this in the current setup, sorry.
