### ISSUE TITLE
TypeError: argument of type 'NoneType" is not iterable.

### ISSUE THREAD

**Issue by ohsnapword** [haijeploeg/excludarr#72]
**Describe the bug**
When running excludarr radarr exclude -a not-monitored -d -e --progress, error on completion.  The results are not formatted as table.

**To Reproduce**
Run excludarr ***arr exclude -a not-monitored -d -e --progress

**Expected behavior**
No error.

**Versions**
1. OS Version: Ubuntu 20.04
2. Excludarr version: 1.06 and 1.07
3. Python version: 3.10.6

**Comment by ohsnapword** [comment]
UPDATE:  I ran the command with sudo and it worked without issue.

**Comment by haijeploeg** [comment]
Hi, cool! Sorry for the late reply, I have taken the development of excludarr on a pause for a while. I am aware of several issues in excludarr and I tend to fix it by creating a Web UI. Where users can control excludarr within an web interface. All the present features will be in there including some new features! I have started the development this week, but it will take some time, I hope to release it before christmas :) PS. I am replying with this message on every issue to make everyone aware.
